version: "3"
services:
  prod:
    container_name: my-portfolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:80"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - SKIP_PREFLIGHT_CHECK=true
